import React from "react";
import WebHeader from "../../components/WebHeader";
import WebFooter from "../../components/WebFooter";
import techBg from "../../assets/web/hero_image.png";

// Helper for section separator
const Separator = () => (
  <div className="h-[4px] bg-gray-200 w-full mt-2 mb-6"></div>
);

export default function WebSolutions() {
  return (
    <div className="font-sans w-full min-h-screen flex flex-col bg-white">
      <WebHeader />

      {/* Banner */}
      <div
        className="w-full h-[200px] flex items-center relative overflow-hidden bg-cover bg-center"
        style={{
          backgroundImage: `url(${techBg})`,
        }}
      >
        <div className="absolute inset-0 bg-black/40"></div>

        <div className="container mx-auto px-6 md:px-12 relative z-10 text-white">
          <h1 className="text-4xl font-bold mb-2">Authentiks Solutions</h1>
          <p className="text-xl text-blue-200">
            Advanced Technology to Protect Your Products
          </p>
        </div>
      </div>

      {/* Content */}
      <main className="flex-grow container mx-auto px-6 md:px-12 py-12 text-[#214B80] max-w-5xl">
        {/* Solutions Intro */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Solutions</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <p className="text-[#214B80] font-medium text-base md:text-lg leading-relaxed">
            Authentiks offers a complete product authentication solution that
            helps brands prevent counterfeits, protect reputation, and build
            consumer trust—at scale.
          </p>
        </div>

        {/* Product Authentication */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Product Authentication</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <p className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            Every product is assigned a unique, secure QR code generated by
            Authentiks. Consumers can peel and scan the code after purchase to
            instantly verify whether the product is genuine.
          </p>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>Counterfeit and duplicate products</li>
              <li>Fake goods entering the supply chain</li>
              <li>Loss of consumer trust</li>
            </ul>
          </div>
        </div>

        {/* Tamper-Proof QR Labels */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Tamper-Proof QR Labels</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <p className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            Our QR codes are printed on tamper-evident peel-and-scan labels.{" "}
            <br />
            Once scanned, the code status updates, making reuse or duplication
            easily detectable.
          </p>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>Reuse of fake QR codes</li>
              <li>Multiple scans of the same product</li>
              <li>Grey market circulation</li>
            </ul>
          </div>
        </div>

        {/* Enterprise QR Code Management */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Enterprise QR Code Management</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <div className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            <p>
              Brands manage everything through the Authentiks Enterprise Portal:
            </p>
            <ul className="list-disc list-inside ml-2">
              <li>Order QR codes</li>
              <li>Approve batches</li>
              <li>Track activation status</li>
              <li>Monitor scans and verification's</li>
            </ul>
          </div>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>Manual tracking errors</li>
              <li>Lack of visibility into product authenticity</li>
              <li>Inefficient verification processes</li>
            </ul>
          </div>
        </div>

        {/* Real-Time Verification Status */}
        <div className="mb-8">
         <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Real-Time Verification Status</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <div className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            <p>Each scan shows a clear result:</p>
            <ul className="list-disc list-inside ml-2">
              <li>Genuine product</li>
              <li>Already verified</li>
              <li>Suspected counterfeit</li>
            </ul>
            <p>This gives consumers clarity and brands instant alerts.</p>
          </div>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>Consumer confusion</li>
              <li>Delayed detection of counterfeit activity</li>
              <li>Brand blind spots</li>
            </ul>
          </div>
        </div>

        {/* Brand Trust & Consumer Confidence */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Brand Trust & Consumer Confidence</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <p className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            Authentiks doesn't just stop counterfeits—it helps brands
            communicate trust. Consumers feel confident knowing authenticity can
            be verified in seconds.
          </p>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>Brand credibility loss</li>
              <li>Customer hesitation</li>
              <li>Post-purchase doubt</li>
            </ul>
          </div>
        </div>

        {/* Scalable for Any Industry */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Scalable for Any Industry</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <p className="text-[#214B80] text-base md:text-lg leading-relaxed mb-4">
            Whether you sell luxury goods, electronics, FMCG, pharmaceuticals,
            automotive parts, or fashion, Authentiks scales with your production
            volume.
          </p>
          <div className="text-base md:text-lg">
            <span className="font-extrabold text-[#214B80]">What it solves</span>
            <ul className="list-disc list-inside text-[#214B80] font-medium ml-2">
              <li>One-size-fits-all tools that don't scale</li>
              <li>Industry-specific compliance challenges</li>
              <li>High-cost anti-counterfeit systems</li>
            </ul>
          </div>
        </div>

        {/* Why Authentiks */}
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
               <h2 className="text-2xl font-bold whitespace-nowrap">Why Authentiks</h2>
               <div className="h-[4px] bg-gray-200 flex-grow"></div>
          </div>
          <div className="text-[#214B80] text-base md:text-lg leading-relaxed font-bold">
            <ul className="list-disc list-inside ml-2 space-y-2">
              <li>Unique QR code for every product</li>
              <li>Simple scan—no app download required</li>
              <li>Secure, tamper-proof system</li>
              <li>Enterprise-grade control</li>
              <li>Consumer-friendly experience</li>
            </ul>
          </div>
        </div>
      </main>
      <WebFooter />
    </div>
  );
}
