const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const generateQrPdf = async (products, creatorEmail) => {
  return new Promise((resolve, reject) => {
     try {
         const doc = new PDFDocument({ margin: 50 });
         let buffers = [];
         
         doc.on("data", buffers.push.bind(buffers));
         doc.on("end", () => {
             const pdfData = Buffer.concat(buffers);
             resolve(pdfData.toString("base64"));
         });

         // Title
         doc.font("Helvetica-Bold").fontSize(20).text("Generated QR Codes", { align: "center" });
         doc.moveDown();
         doc.fontSize(10).text(`Generated By: ${creatorEmail}`, { align: "center" });
         doc.moveDown(2);

         let x = 50;
         let y = 150;
         const qrSize = 100;
         const margin = 20;

         (async () => {
             for (let i = 0; i < products.length; i++) {
                 const product = products[i];
                 
                 // If we run out of vertical space, add page
                 if (y + qrSize + 50 > doc.page.height - 50) {
                     doc.addPage();
                     y = 50;
                 }

                 // Generate QR Image Buffer
                 const qrBuffer = await QRCode.toBuffer(product.qrCode);
                 
                 // Draw QR
                 doc.image(qrBuffer, x, y, { width: qrSize, align: 'center' });
                 
                 // Text Details
                 doc.font("Helvetica-Bold").fontSize(10)
                    .text(product.qrCode, x + qrSize + margin, y + 10);
                 
                 doc.font("Helvetica").fontSize(10)
                    .text(`Product: ${product.productName}`, x + qrSize + margin, y + 25)
                    .text(`Brand: ${product.brand}`, x + qrSize + margin, y + 40)
                    .text(`Batch: ${product.batchNo}`, x + qrSize + margin, y + 55);
                 
                 y += qrSize + margin + 20;
             }
             
             doc.end();
         })();

     } catch (err) {
         reject(err);
     }
  });
};

module.exports = { generateQrPdf };
